require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - Gemfile
    - Rakefile

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/AbcSize:
  Max: 25
  
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude: []
  ExcludedMethods:
    - describe
    - fdescribe
    - context
    - fcontext
    - it
    - fit
    - shared_examples_for
    - shared_context
    - source

Style/SignalException:
  Enabled: false

Style/Documentation:
  Enabled: false
