version: '2.1'

orbs:
  slack: circleci/slack@2.5.0
  
default_bundle_env: &default_bundle_env
  environment:
    BUNDLE_JOBS: 7
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle

default_job: &default_job
  steps:
    - checkout
    - build
    - test

executors:
  ruby-2-4-4:
    docker:
      - image: circleci/ruby:2.4.4
        <<: *default_bundle_env

  ruby-2-5-5:
    docker:
      - image: circleci/ruby:2.5.5
        <<: *default_bundle_env

  ruby-2-6-3:
    docker:
      - image: circleci/ruby:2.6.3
        <<: *default_bundle_env

commands:
  build:
    description: 'Install gems'
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}
      - run: bundle check || bundle install
      - save_cache:
          key: gem-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle
  test:
    description: 'Run rspec'
    steps:
      - type: shell
        command: |
          mkdir /tmp/test-results
          bundle exec rspec --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - slack/status:
          fail_only: 'true'
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

jobs:
  test-2-4-4:
    executor: ruby-2-4-4
    <<: *default_job

  test-2-5-5:
    executor: ruby-2-5-5
    <<: *default_job

  test-2-6-3:
    executor: ruby-2-6-3
    <<: *default_job

workflows:
  commit:
    jobs:
      - test-2-4-4
      - test-2-5-5
      - test-2-6-3
