version: 2.1

executors:
  ruby-2-4-4:
    docker:
      - image: circleci/ruby:2.4.4
        environment:
          BUNDLE_JOBS: 7
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

  ruby-2-6-3:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          BUNDLE_JOBS: 7
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

commands:
  build:
    description: 'Install gems'
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test:
    description: 'Run rspec'
    steps:
      - run: COV=true rspec

jobs:
  test-2-4-4:
    executor: ruby-2-4-4
    steps:
      - checkout
      - build
      - test

  test-2-6-3:
    executor: ruby-2-6-3
    steps:
      - checkout
      - build
      - test

workflows:
  commit:
    jobs:
      - test-2-4-4
      - test-2-6-3
