version: 2.1

orbs:
  base: codacy/base@0.0.4

executors:
  ruby-2-4-4:
    docker:
      - image: circleci/ruby:2.4.4
  ruby-2-6-3:
    docker:
      - image: circleci/ruby:2.6.3

commands:
  build:
    description: 'Install gems'
    steps:
      - run: bundle install
  test:
    description: 'Run rspec'
    steps:
      - run: COV=true rspec

jobs:
  test-2-4-4:
    executor: ruby-2.4.4
    steps:
      - checkout
      - build
      - test

  test-2-6-3:
    executor: ruby-2-6-3
    steps:
      - checkout
      - build
      - test

workflows:
  commit:
    jobs:
      - test-2-4-4
      - test-2-6-3
