version: 2.1

defaults:
  default_bundle_env: &default_bundle_env
  environment:
    BUNDLE_JOBS: 7
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle

  default_job: &default_job
  steps:
    - checkout
    - build
    - test

executors:
  ruby-2-4-4:
    docker:
      - image: circleci/ruby:2.4.4
        <<: *default_bundle_env

  ruby-2-5-5:
    docker:
      - image: circleci/ruby:2.5.5
        <<: *default_bundle_env

  ruby-2-6-3:
    docker:
      - image: circleci/ruby:2.6.3
        <<: *default_bundle_env

commands:
  build:
    description: 'Install gems'
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}
      - run: bundle install
      - save_cache:
          key: gem-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle
  test:
    description: 'Run rspec'
    steps:
      - run: COV=true bundle exec rspec

jobs:
  test-2-4-4:
    executor: ruby-2-4-4
    <<: *default_job

  test-2-5-5:
    executor: ruby-2-5-5
    <<: *default_job

  test-2-6-3:
    executor: ruby-2-6-3
    <<: *default_job

workflows:
  commit:
    jobs:
      - test-2-4-4
      - test-2-5-5
      - test-2-6-3
